### ISSUE TITLE
Tasks that occur every 30 seconds

### ISSUE THREAD

**Issue by gusilveiramp** [jamesisaac/react-native-background-task#18]
Hi @jamesisaac 
I'm working with background geolocation and need it to run a check every 30 seconds to check if the user is in a certain location and send a push. I set the "priod" to 60, but nothing happens when the app goes to background.

Is it possible to work this way with your library?

**Comment by jamesisaac** [comment]
Hi there,

Both iOS and Android enforce a minimum period of 15 minutes on the type of scheduling used by this library.

For your use case, I'd recommend something more purpose-built, like this:
https://github.com/transistorsoft/react-native-background-geolocation

**Comment by mun3** [comment]
@jamesisaac Is the 15 min limitation due to iOS/Android policies or purely out of courtesy?
