### ISSUE TITLE
why not using this react-native-background-fetch itself?

### ISSUE THREAD

**Issue by sibelius** [jamesisaac/react-native-background-task#26]
What are the limitations of this react-native-background-fetch?

What are the advantages of this package?

**Comment by jamesisaac** [comment]
Android support is a new addition to the react-native-background-fetch library (added just under a month ago it looks like).  While the initial goal of this library, from the first release about a year ago, has always been cross-platform support.

I can have a closer look at and comment on the implementation differences when I get a chance, but at a quick glance it looks like both libraries are probably more or less achieving the same thing.

**Comment by sibelius** [comment]
Tks
