### ISSUE TITLE
Single periodic task?

### ISSUE THREAD

**Issue by joeabill** [jamesisaac/react-native-background-task#55]
Sorry, this is probably a stupid question but I want to clear this up before I get too involved with this module. The readme says "This library allows the scheduling of a single periodic task" so I am a little confused if I can do multiple "tasks". For example, say I want to make 3 web services calls (with different intervals) and do something with the responses.

**Comment by jamesisaac** [comment]
The platform limitation on both platforms is one background task per ~15 mins.  You can't bypass that and have things more frequent than that by having multiple tasks.

However, of course you could have your own logic within the task which e.g. executes 1 of 3 code paths depending on a stored value of what was executed last time.

**Comment by joeabill** [comment]
That's what I thought. Thank you for your response and the awesome module!
